version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - db-volume:/app/instance
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-SomeSecret}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-Admin123}
      - TEST_USER1_PASSWORD=${TEST_USER1_PASSWORD:-TestUser1}
      - TEST_USER2_PASSWORD=${TEST_USER2_PASSWORD:-TestUser2}
      - TEST_USER3_PASSWORD=${TEST_USER3_PASSWORD:-TestUser3}
      - TEST_USER4_PASSWORD=${TEST_USER4_PASSWORD:-TestUser4}
      - TEST_USER5_PASSWORD=${TEST_USER5_PASSWORD:-TestUser5}
      - TEST_USER6_PASSWORD=${TEST_USER6_PASSWORD:-TestUser6}
      - TEST_USER7_PASSWORD=${TEST_USER7_PASSWORD:-TestUser7}
      - TEST_USER8_PASSWORD=${TEST_USER8_PASSWORD:-TestUser8}
      - TEST_USER9_PASSWORD=${TEST_USER9_PASSWORD:-TestUser9}

volumes:
  db-volume:
