FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Accept build arguments for secrets (can be passed via --build-arg)
ARG FLASK_SECRET_KEY=SomeSecret
ARG ADMIN_PASSWORD=Admin123
ARG TEST_USER1_PASSWORD=TestUser1
ARG TEST_USER2_PASSWORD=TestUser2
ARG TEST_USER3_PASSWORD=TestUser3
ARG TEST_USER4_PASSWORD=TestUser4
ARG TEST_USER5_PASSWORD=TestUser5
ARG TEST_USER6_PASSWORD=TestUser6
ARG TEST_USER7_PASSWORD=TestUser7
ARG TEST_USER8_PASSWORD=TestUser8
ARG TEST_USER9_PASSWORD=TestUser9

# Set environment variables from build arguments
ENV FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
ENV ADMIN_PASSWORD=${ADMIN_PASSWORD}
ENV TEST_USER1_PASSWORD=${TEST_USER1_PASSWORD}
ENV TEST_USER2_PASSWORD=${TEST_USER2_PASSWORD}
ENV TEST_USER3_PASSWORD=${TEST_USER3_PASSWORD}
ENV TEST_USER4_PASSWORD=${TEST_USER4_PASSWORD}
ENV TEST_USER5_PASSWORD=${TEST_USER5_PASSWORD}
ENV TEST_USER6_PASSWORD=${TEST_USER6_PASSWORD}
ENV TEST_USER7_PASSWORD=${TEST_USER7_PASSWORD}
ENV TEST_USER8_PASSWORD=${TEST_USER8_PASSWORD}
ENV TEST_USER9_PASSWORD=${TEST_USER9_PASSWORD}

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

RUN rm -rf /app/instance && mkdir -p /app/instance && chmod -R 777 /app/instance

EXPOSE 5000

RUN python -c "from app import initDB; initDB()"

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app:app"]